## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Mike Lapidakis"
theme = "hugo-story"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "Mike Lapidakis is a technology enthusiast and AWS specialist from Denver, Colorado. He manages specialist solutions architects at Amazon Web Services (AWS), where he helps organizations optimize their cloud strategies. Outside of work, Mike writes extensively on his blog, Empty Coffee, covering topics such as self-hosted services, cloud infrastructure, and digital security. His writing is known for its clarity and practical advice, making complex tech topics accessible. An outdoor enthusiast, Mike enjoys running, biking, hiking, and camping with his family. He also speaks at industry events, sharing his expertise on cloud security and generative AI."
  logo = "MikeLapidakis.jpg"
  favicon = true
  url = "https://mike.lapidak.is"
  siteImage = "https://mike.lapidak.is/cdn-cgi/imagedelivery/3iqqzuCu4mz697Mt3VX2wA/4f7e1c06-371c-42a5-4c36-d611ac213900/post"

[Params.social]
  github = "https://github.com/mlapida/"
  photos = "https://glass.photo/lap"
  mastodon = "https://me.dm/@mike"
  x = "https://x.com/MikeLapidakis"
  threads = "https://www.threads.net/@mikelapidakis"
  linkedin = "https://linkedin.com/in/MikeLapidakis"
  blog = "https://empty.coffee/"
  bluesky = "https://bsky.app/profile/mike.lapidak.is"